import type { Script } from "./types";

const FALLBACK_SCRIPTS: Script[] = [
  {
    topic: "My Daily Routine",
    category: "Daily Life",
    turns: [
      { speaker: "coach", text: "Hi! Let's talk about your daily routine. What time do you usually wake up?" },
      { speaker: "user", text: "I usually wake up at seven in the morning.", hint: "I usually wake up at seven in the morning." },
      { speaker: "coach", text: "That's a great start to the day! What do you do first after waking up?" },
      { speaker: "user", text: "First I brush my teeth and then I have breakfast.", hint: "First I brush my teeth and then I have breakfast." },
      { speaker: "coach", text: "Good habits! What do you normally eat for breakfast?" },
      { speaker: "user", text: "I usually eat toast and drink a cup of coffee.", hint: "I usually eat toast and drink a cup of coffee." },
      { speaker: "coach", text: "Sounds delicious! How do you get to work or school?" },
      { speaker: "user", text: "I take the subway. It takes about thirty minutes.", hint: "I take the subway. It takes about thirty minutes." },
      { speaker: "coach", text: "That's quite a commute. What time do you usually finish your day?" },
      { speaker: "user", text: "I finish work at around six in the evening.", hint: "I finish work at around six in the evening." },
      { speaker: "coach", text: "And what do you like to do to relax in the evening?" },
      { speaker: "user", text: "I like to watch TV or read a book before going to bed.", hint: "I like to watch TV or read a book before going to bed." },
    ],
  },
  {
    topic: "My Job",
    category: "Work & Career",
    turns: [
      { speaker: "coach", text: "Let's talk about your work! What do you do for a living?" },
      { speaker: "user", text: "I work as a software engineer at a tech company.", hint: "I work as a software engineer at a tech company." },
      { speaker: "coach", text: "That sounds interesting! How long have you been in that role?" },
      { speaker: "user", text: "I have been working there for about three years.", hint: "I have been working there for about three years." },
      { speaker: "coach", text: "What do you enjoy most about your job?" },
      { speaker: "user", text: "I enjoy solving problems and learning new technologies.", hint: "I enjoy solving problems and learning new technologies." },
      { speaker: "coach", text: "That's a great attitude. What's the most challenging part?" },
      { speaker: "user", text: "The most challenging part is managing tight deadlines.", hint: "The most challenging part is managing tight deadlines." },
      { speaker: "coach", text: "Do you work in an office or from home?" },
      { speaker: "user", text: "I work from home three days a week and go to the office twice.", hint: "I work from home three days a week and go to the office twice." },
      { speaker: "coach", text: "Hybrid work sounds flexible! What are your career goals?" },
      { speaker: "user", text: "I hope to become a team leader in the next couple of years.", hint: "I hope to become a team leader in the next couple of years." },
    ],
  },
  {
    topic: "A Recent News Story",
    category: "News & Society",
    turns: [
      { speaker: "coach", text: "Let's discuss the news! Have you read or heard any interesting stories lately?" },
      { speaker: "user", text: "Yes, I read about advances in artificial intelligence this week.", hint: "Yes, I read about advances in artificial intelligence this week." },
      { speaker: "coach", text: "That's a hot topic! What did the story say?" },
      { speaker: "user", text: "It said that AI can now help doctors diagnose diseases more accurately.", hint: "It said that AI can now help doctors diagnose diseases more accurately." },
      { speaker: "coach", text: "That's fascinating. How do you feel about AI being used in medicine?" },
      { speaker: "user", text: "I think it's very helpful, but doctors should still make the final decisions.", hint: "I think it's very helpful, but doctors should still make the final decisions." },
      { speaker: "coach", text: "Good point. Do you think this technology will change healthcare significantly?" },
      { speaker: "user", text: "Definitely. It could save a lot of lives by catching problems earlier.", hint: "Definitely. It could save a lot of lives by catching problems earlier." },
      { speaker: "coach", text: "Are there any concerns about AI that worry you?" },
      { speaker: "user", text: "I am a bit worried about privacy and how patient data is used.", hint: "I am a bit worried about privacy and how patient data is used." },
    ],
  },
  {
    topic: "A Favorite Movie",
    category: "Entertainment & Culture",
    turns: [
      { speaker: "coach", text: "Let's talk about movies! What's a film you really enjoyed recently?" },
      { speaker: "user", text: "I really enjoyed watching Interstellar. It was amazing.", hint: "I really enjoyed watching Interstellar. It was amazing." },
      { speaker: "coach", text: "Oh that's a classic! What did you like about it?" },
      { speaker: "user", text: "I loved the story about space travel and the special effects were incredible.", hint: "I loved the story about space travel and the special effects were incredible." },
      { speaker: "coach", text: "Did any part of the movie surprise you?" },
      { speaker: "user", text: "Yes, the ending was very unexpected and emotional.", hint: "Yes, the ending was very unexpected and emotional." },
      { speaker: "coach", text: "Would you recommend it to a friend? How would you describe it?" },
      { speaker: "user", text: "Absolutely! I would say it's a must-watch for anyone who loves science fiction.", hint: "Absolutely! I would say it's a must-watch for anyone who loves science fiction." },
      { speaker: "coach", text: "Great recommendation. Do you have a favorite actor or director?" },
      { speaker: "user", text: "I really like Christopher Nolan. He makes very creative and intelligent films.", hint: "I really like Christopher Nolan. He makes very creative and intelligent films." },
    ],
  },
  {
    topic: "Weekend Plans",
    category: "Daily Life",
    turns: [
      { speaker: "coach", text: "The weekend is almost here! Do you have any plans?" },
      { speaker: "user", text: "Yes, I'm planning to go hiking with some friends on Saturday.", hint: "Yes, I'm planning to go hiking with some friends on Saturday." },
      { speaker: "coach", text: "That sounds fun! Where are you going hiking?" },
      { speaker: "user", text: "We are going to a mountain trail about an hour outside the city.", hint: "We are going to a mountain trail about an hour outside the city." },
      { speaker: "coach", text: "How long is the hike? Is it difficult?" },
      { speaker: "user", text: "It's about five kilometers and it's moderately challenging.", hint: "It's about five kilometers and it's moderately challenging." },
      { speaker: "coach", text: "Nice! What about Sunday — any plans?" },
      { speaker: "user", text: "On Sunday I plan to stay home, rest, and maybe do some cooking.", hint: "On Sunday I plan to stay home, rest, and maybe do some cooking." },
      { speaker: "coach", text: "Sounds like a perfect balance of activity and relaxation. What will you cook?" },
      { speaker: "user", text: "I want to try making pasta from scratch. I found a good recipe online.", hint: "I want to try making pasta from scratch. I found a good recipe online." },
    ],
  },
];

export default FALLBACK_SCRIPTS;
